"""
svg_common.py

Small, dependency-free (stdlib only) helpers shared by scripts/stats.py and
scripts/make_heading.py so every generated graphic in assets/svg/ shares one
visual language:

    - monospace text set in an embedded JetBrains Mono subset
    - a single foreground color (light-mode / dark-mode aware, but never
      more than one hue at a time -- no rainbow-per-element coloring)
    - a base64 data: URI @font-face declared inside an inline <style>, which
      is same-document CSS and therefore survives GitHub's markdown/SVG
      sanitizer (external stylesheets and <script> do not).

Font subsetting happens ONCE, ahead of time (see assets/fonts/subset/), not
at workflow run time -- see the note in stats.py's module docstring for why.
This module only reads the already-subset .ttf files and base64-encodes them.
"""
from __future__ import annotations

import base64
from pathlib import Path
from xml.sax.saxutils import escape as _escape

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = REPO_ROOT / "assets" / "fonts"
SUBSET_DIR = FONTS_DIR / "subset"

# Pre-subset font files (committed to the repo, generated once with
# `py -m fontTools.subset`, NOT regenerated by the nightly workflow):
FONT_TEXT_PATH = SUBSET_DIR / "jbm-text.ttf"   # basic latin (U+0020-007E)
FONT_RAMP_PATH = SUBSET_DIR / "jbm-ramp.ttf"   # only the year.svg ramp glyphs

# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------
# JetBrains Mono is a true monospace font: every glyph (including space) has
# an advance width of exactly 600 units against a 1000 unitsPerEm grid, i.e.
# 0.6em. Measured directly off the font with fontTools once, at subsetting
# time -- hardcoded here so stats.py never needs fontTools at *runtime*.
MONO_ADVANCE_RATIO = 0.6


def text_width(s: str, font_size: float) -> float:
    """Width in px of a monospace string set at font_size."""
    return len(s) * font_size * MONO_ADVANCE_RATIO


# ---------------------------------------------------------------------------
# Color -- ONE foreground color, shared with the portrait
# ---------------------------------------------------------------------------
# One deliberate accent color, shared with the portrait, instead of a
# generic default gray/green/blue: a warm copper (#a86a2e), checked for
# real contrast rather than eyeballed -- ~4.4:1 on GitHub light (#ffffff)
# and ~4.3:1 on GitHub dark (#0d1117), so a single flat value reads fine on
# both without a prefers-color-scheme branch. We reuse this exact value
# here so every generated graphic in the README -- portrait and stats
# alike -- speaks the same one-color visual language.
FILL_COLOR = "#a86a2e"
MUTED_OPACITY = "0.65"  # secondary/caption text: same hue, lower opacity -- still one color


def esc(s: object) -> str:
    return _escape(str(s))


# ---------------------------------------------------------------------------
# Font loading
# ---------------------------------------------------------------------------
def load_font_base64(path: Path) -> str:
    data = path.read_bytes()
    return base64.b64encode(data).decode("ascii")


def font_face_css(family: str, font_path: Path) -> str:
    b64 = load_font_base64(font_path)
    return (
        "@font-face{"
        f"font-family:'{family}';"
        f"src:url(data:font/ttf;base64,{b64}) format('truetype');"
        "font-weight:400;font-style:normal;"
        "}"
    )


def style_block(*, families: list[tuple[str, Path]], text_family: str) -> str:
    """Build the <style> body: font-faces + one-color base rules.

    Deliberately no prefers-color-scheme branch: a single flat fill color
    (matching scripts/make_portrait.py's FILL_COLOR) that already reads fine
    in both GitHub themes is simpler and more literally "one fill color"
    than swapping between a light-mode and dark-mode shade.
    """
    faces = "".join(font_face_css(name, path) for name, path in families)
    return (
        faces
        + "text{"
        f"font-family:'{text_family}','JetBrains Mono',ui-monospace,Consolas,monospace;"
        "}"
        ".fg{fill:" + FILL_COLOR + ";}"
        ".muted{fill:" + FILL_COLOR + ";fill-opacity:" + MUTED_OPACITY + ";}"
        ".stroke-fg{stroke:" + FILL_COLOR + ";}"
        ".stroke-muted{stroke:" + FILL_COLOR + ";stroke-opacity:" + MUTED_OPACITY + ";}"
        ".bg{fill:none;}"
    )


def svg_document(width: int, height: int, style_css: str, body: str, *, title: str = "") -> str:
    """Wrap a body of SVG markup into a complete, well-formed <svg> document."""
    title_el = f"<title>{esc(title)}</title>" if title else ""
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width}" height="{height}" viewBox="0 0 {width} {height}" '
        'role="img">'
        + title_el
        + f"<style>{style_css}</style>"
        + body
        + "</svg>"
    )
